stages:
  
  environment:
    cmd: bash stages/00_environment.sh
  
  download:
    cmd: python stages/01_download.py
    deps:
      - stages/01_download.py
    outs:
      - download
  
  process:
    cmd: python stages/02_process.py
    deps:
      - stages/02_process.py
    outs:
      - download

  verify:
    cmd: python stages/03_verify.py
    deps:
      - stages/02_process.py
    outs:
      - download

  build: 
    cmd: python stages/04_build.py
    deps:
      - stages/03_verify.py
      - download
    outs:
      - brick
