stages:
  
  environment:
    cmd: bash stages/00_environment.sh
  
  download:
    cmd: python3 stages/01_download.py
    deps:
      - stages/01_download.py
    outs:
      - download
  
  process:
    cmd: python3 stages/02_process.py
    deps:
      - stages/02_process.py
    outs:
      - process

  verify:
    cmd: python3 stages/03_verify.py
    deps:
      - stages/02_process.py
    outs:
      - verify

  build: 
    cmd: python3 stages/04_build.py
    deps:
      - stages/04_build.py
      - download
      - verify
    outs:
      - brick
